all: libphidget

TARBALL = build/libphidget_2.1.8.20120716.tar.gz
TARBALL_URL = http://www.phidgets.com/downloads/libraries/libphidget_2.1.8.20120716.tar.gz
SOURCE_DIR = build/libphidget_2.1.8.20120716

include $(shell rospack find mk)/download_unpack_build.mk

libphidget: $(SOURCE_DIR)
	cd $(SOURCE_DIR) && ./configure
	cd $(SOURCE_DIR) && make
clean:
	rm -rf common $(SOURCE_DIR) $(TARBALL)
wipe: clean
	-rm -rf build
